version: "2.1"

services:
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  web:
    image: rails-dfe-boilerplate
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db

  webpacker:
    build: .
    env_file:
      - ".env.docker"
    command: ./bin/webpack-dev-server
    volumes:
      - .:/webpacker-example-app
    ports:
      - "3035:3035"
